name: Run Issue Resolver

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '0 * * * *'  # Optional: every hour

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14.0  # ✅ CORRECTED VERSION

      - name: Install dependencies
        run: pip install requests google-generativeai

      - name: Run Issue Resolver
        run: python script.py
        env:
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
